import { permissionDefinitions, type PermissionKey } from "./permissions";
import { ROLE_KEYS, type RoleKey } from "./roles";

const allPermissionKeys = permissionDefinitions.map(({ key }) => key);

function permissions<const Keys extends readonly PermissionKey[]>(...keys: Keys): Keys {
  return keys;
}

export const INITIAL_ROLE_PERMISSION_MATRIX = {
  [ROLE_KEYS.INTERNAL_CEO_CTO]: allPermissionKeys,
  [ROLE_KEYS.INTERNAL_ADMIN]: allPermissionKeys,
  [ROLE_KEYS.INTERNAL_KEY_ACCOUNT_MANAGER]: permissions(
    "dashboard:view",
    "clients:view",
    "clients:edit",
    "clients:export",
    "crm:view",
    "crm:create",
    "crm:edit",
    "crm:export",
    "hrm:view",
    "vms:view",
    "bms:view",
    "vault:view",
    "internal_chat:view",
    "internal_chat:create",
    "internal_chat:edit",
    "marketing:view",
    "accounts:view",
  ),
  [ROLE_KEYS.INTERNAL_COMPANY_SECRETARY]: permissions(
    "dashboard:view",
    "clients:view",
    "bms:view",
    "bms:create",
    "bms:edit",
    "bms:approve",
    "bms:export",
    "vault:view",
    "vault:create",
    "vault:edit",
    "vault:export",
    "internal_chat:view",
    "internal_chat:create",
    "internal_chat:edit",
  ),
  [ROLE_KEYS.INTERNAL_CA]: permissions(
    "dashboard:view",
    "clients:view",
    "accounts:view",
    "accounts:create",
    "accounts:edit",
    "accounts:approve",
    "accounts:export",
    "vault:view",
    "vault:create",
    "vault:edit",
    "vault:export",
    "internal_chat:view",
    "internal_chat:create",
  ),
  [ROLE_KEYS.INTERNAL_ACCOUNTANT]: permissions(
    "dashboard:view",
    "clients:view",
    "accounts:view",
    "accounts:create",
    "accounts:edit",
    "accounts:export",
    "vault:view",
    "vault:create",
    "vault:edit",
    "internal_chat:view",
    "internal_chat:create",
  ),
  [ROLE_KEYS.INTERNAL_DESIGNER]: permissions(
    "dashboard:view",
    "clients:view",
    "marketing:view",
    "marketing:create",
    "marketing:edit",
    "marketing:export",
    "vault:view",
    "vault:create",
    "vault:edit",
    "internal_chat:view",
    "internal_chat:create",
    "internal_chat:edit",
  ),
  [ROLE_KEYS.INTERNAL_SME]: permissions(
    "dashboard:view",
    "clients:view",
    "crm:view",
    "hrm:view",
    "vms:view",
    "bms:view",
    "vault:view",
    "internal_chat:view",
    "internal_chat:create",
    "internal_chat:edit",
    "marketing:view",
    "accounts:view",
  ),
  [ROLE_KEYS.INTERNAL_SALES]: permissions(
    "dashboard:view",
    "clients:view",
    "clients:create",
    "clients:edit",
    "clients:export",
    "crm:view",
    "crm:create",
    "crm:edit",
    "crm:export",
    "internal_chat:view",
    "internal_chat:create",
    "internal_chat:edit",
    "marketing:view",
  ),
  [ROLE_KEYS.CLIENT_OWNER]: permissions(
    "dashboard:view",
    "clients:view",
    "clients:edit",
    "clients:export",
    "crm:view",
    "crm:create",
    "crm:edit",
    "crm:delete",
    "crm:export",
    "hrm:view",
    "hrm:create",
    "hrm:edit",
    "hrm:delete",
    "hrm:approve",
    "hrm:export",
    "vms:view",
    "vms:create",
    "vms:edit",
    "vms:delete",
    "vms:approve",
    "vms:export",
    "bms:view",
    "bms:create",
    "bms:edit",
    "bms:delete",
    "bms:approve",
    "bms:export",
    "vault:view",
    "vault:create",
    "vault:edit",
    "vault:delete",
    "vault:export",
    "marketing:view",
    "marketing:create",
    "marketing:edit",
    "marketing:delete",
    "marketing:approve",
    "marketing:export",
    "accounts:view",
    "accounts:create",
    "accounts:edit",
    "accounts:delete",
    "accounts:approve",
    "accounts:export",
  ),
} as const satisfies Record<RoleKey, readonly PermissionKey[]>;
